In [29]:
import numpy as np
# marks=np.array([90,90,80])
# marks+5


In [2]:
import numpy as np      # ipynb - interactive python notebook
# it is writtten in c language and it is used as python. 
#  Since python has no array we use numpy library
# it is used for storing multidimensional data and can perform many operations and process data

# to add 5 marks for every marks
marks=np.array([80,90,78,88,98])
marks+5
marks/2
marks+5 # here we are just calculating and not printing

array([ 85,  95,  83,  93, 103])

In [3]:
marks=marks-5  # here we store the value and printing
marks/2
print(marks)

[75 85 73 83 93]


In [4]:
# Traversing
for i in range(4):
    print(marks[i])

75
85
73
83


In [5]:
# slicing
marks[:2]

array([75, 85])

In [6]:
# slicing
marks[1:4]

array([85, 73, 83])

In [7]:
# 2D array
marks=np.array([
    [85,78,90],
    [92,85,98],
    [76,82,80]]
    )
# rows -> students
# cloumns -> marks

In [8]:
print(marks)

[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [9]:
# marks[0,0]

In [10]:
# marks[0][0]

In [11]:
marks[2,1]

np.int64(82)

In [12]:
# marks[0][2]

In [13]:
# 1st row(means here index is 1)and 0th column
# marks[1:,0]

In [14]:
# print(marks[1:,0])
# print(marks[0:][0])

In [15]:
# [1:,0] = NumPy slicing (2D aware)
# [1:][0] = List slicing (1D at a time)

# ✅ Use marks[1:,0] for NumPy arrays!

# print(marks[1:,0])
# print(marks[1:][0])

In [16]:
# numpy slicing
# marks[0,0:2]

In [17]:
# actual slicing
marks[0][0:2]

array([85, 78])

In [18]:
# b1 b2 means 2 types  of batches
b1=np.array([56,78,89])
b2=np.array([65,76,98])

# combine those 2 batches marks
comb=np.concatenate((b1,b2))
comb

array([56, 78, 89, 65, 76, 98])

In [19]:
# axis(in rows and columns)
# ques : A combined dataset contains 6 students. The academic team wants the data into two groups for separate processing.
np.split(comb,2)

[array([56, 78, 89]), array([65, 76, 98])]

In [20]:
# axis(in rows and columns)
# ques : A combined dataset contains 6 students. The academic team wants the data into two groups for separate processing.
print(np.split(comb,2))

[array([56, 78, 89]), array([65, 76, 98])]


In [21]:
# axis(in rows and columns)
# ques : A combined dataset contains 6 students. The academic team wants the data into two groups for separate processing.
np.split(comb,2)

for arr in np.split(comb,2):
    print(arr)

[56 78 89]
[65 76 98]


In [22]:
# axis(in rows and columns)
# ques : A combined dataset contains 6 students. The academic team wants the data into three groups for separate processing.
np.split(comb,2)

for arr in np.split(comb,3):
    print(arr)

[56 78]
[89 65]
[76 98]


In [23]:
# b1 b2 means 2 types  of batches
b1=np.array([56,78,89])
b2=np.array([65,76,98])

# combine those 2 batches marks
comb=np.concatenate((b1,b2),axis=0)
comb

array([56, 78, 89, 65, 76, 98])

In [24]:
# here => Axis=0 ->X -> Rows  and Axis=1 ->y -> columns

b1=np.array([
    [56,78,89],
    [34,45,67]
])
b2=np.array([
    [85,78,90],
    [89,98,78]
])

comb1=np.concatenate((b1,b2),axis=1)
# array([[56 78 89 85 78 90],
#  [34 45 67 89 98 78]])
print(comb1)
print("--------------")
comb0=np.concatenate((b1,b2),axis=0)
comb0

[[56 78 89 85 78 90]
 [34 45 67 89 98 78]]
--------------


array([[56, 78, 89],
       [34, 45, 67],
       [85, 78, 90],
       [89, 98, 78]])

In [25]:
# to find where the mark is 78
np.where(marks==78)

(array([0]), array([1]))

In [26]:
# to find where the mark where mark is >70
np.where(marks>78)
print(marks)

[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [32]:
mark=np.array([85,78,90],
              [92,85,98],
              [76,82,80])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
# it sorting it in row  vise
np.sort(marks)

# reverse the complete arrary
np.sort(marks)[::-1]

array([[76, 80, 82],
       [85, 92, 98],
       [78, 85, 90]])

In [ ]:
# column vise sorting
np.sort(marks,axis=1)

array([[78, 85, 90],
       [85, 92, 98],
       [76, 80, 82]])

In [ ]:
# column vise sorting
np.sort(marks,axis=0)

array([[76, 78, 80],
       [85, 82, 90],
       [92, 85, 98]])

In [40]:
arr=np.array(['Ram',45,67,9.0,'True'])
print(arr)
print(type(arr))


['Ram' '45' '67' '9.0' 'True']
<class 'numpy.ndarray'>
